"""LLM service for autonomous historical riddle generation."""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from typing import Any, Final

from openai import (
    APIConnectionError,
    AsyncOpenAI,
    AuthenticationError,
    OpenAIError,
    RateLimitError,
)

logger = logging.getLogger(__name__)

SYSTEM_PROMPT: Final[str] = (
    "Ты историк-криптограф. Сгенерируй малоизвестный, но интересный исторический факт "
    "в виде загадки (до 300 символов) и ответ на нее."
)

USER_PROMPT: Final[str] = (
    "Сформулируй одну историческую загадку и её точный ответ. "
    "Загадка должна быть не длиннее 300 символов. "
    'Верни JSON строго в формате: {"riddle": "текст загадки", "answer": "ответ"}.'
)

MAX_RIDDLE_LENGTH: Final[int] = 300


class LLMServiceError(Exception):
    """Base exception for LLM service failures."""


class LLMConfigurationError(LLMServiceError):
    """Raised when required LLM configuration is missing."""


class LLMAuthenticationError(LLMServiceError):
    """Raised when the LLM provider rejects the API key."""


class LLMRateLimitError(LLMServiceError):
    """Raised when the LLM provider rate limit is exceeded."""


class LLMConnectionError(LLMServiceError):
    """Raised when the LLM provider cannot be reached."""


class LLMResponseError(LLMServiceError):
    """Raised when the LLM response cannot be parsed or validated."""


@dataclass(frozen=True, slots=True)
class HistoryRiddle:
    """Historical riddle generated by the LLM."""

    riddle: str
    answer: str

    def embedding_text(self) -> str:
        """Return the text that should be hidden inside the steganographic image."""
        return self.riddle


class HistoryRiddleGenerator:
    """Generate historical riddles through the OpenAI Chat Completions API."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        model: str | None = None,
        client: AsyncOpenAI | None = None,
    ) -> None:
        """Initialize the generator.

        Args:
            api_key: OpenAI API key. Falls back to ``OPENAI_API_KEY`` env var.
            model: Model name. Falls back to ``OPENAI_MODEL`` or ``gpt-4o-mini``.
            client: Optional pre-configured AsyncOpenAI client for testing.
        """
        resolved_key = (api_key or os.getenv("OPENAI_API_KEY") or "").strip()
        if not resolved_key:
            raise LLMConfigurationError(
                "OPENAI_API_KEY is not configured. Add a valid API key to the .env file."
            )

        self.model = model or os.getenv("OPENAI_MODEL", "gpt-4o-mini")
        self._client = client or AsyncOpenAI(api_key=resolved_key)

    async def generate_riddle(self) -> HistoryRiddle:
        """Generate a historical riddle via the LLM.

        Returns:
            Parsed and validated :class:`HistoryRiddle`.

        Raises:
            LLMAuthenticationError: If the API key is invalid or expired.
            LLMRateLimitError: If provider rate limits are exceeded.
            LLMConnectionError: If the provider cannot be reached.
            LLMResponseError: If the model response is empty or malformed.
            LLMServiceError: For other upstream OpenAI failures.
        """
        try:
            content = await self._request_completion()
            parsed = self._parse_response(content)
            return HistoryRiddle(riddle=parsed["riddle"], answer=parsed["answer"])
        except AuthenticationError as exc:
            logger.error("OpenAI authentication failed: %s", exc)
            raise LLMAuthenticationError(
                "OpenAI API key is invalid or expired. Check OPENAI_API_KEY in .env."
            ) from exc
        except RateLimitError as exc:
            logger.error("OpenAI rate limit exceeded: %s", exc)
            raise LLMRateLimitError(
                "OpenAI rate limit exceeded. Try again later or upgrade your plan."
            ) from exc
        except APIConnectionError as exc:
            logger.error("OpenAI connection error: %s", exc)
            raise LLMConnectionError(
                "Unable to connect to OpenAI. Check your network connection and try again."
            ) from exc
        except (json.JSONDecodeError, KeyError, ValueError) as exc:
            logger.error("Invalid LLM response payload: %s", exc)
            raise LLMResponseError(
                "OpenAI returned an invalid riddle payload. Expected JSON with 'riddle' and 'answer'."
            ) from exc
        except OpenAIError as exc:
            logger.error("Unexpected OpenAI error: %s", exc)
            raise LLMServiceError(f"OpenAI request failed: {exc}") from exc

    async def _request_completion(self) -> str:
        """Call OpenAI and return the raw model content."""
        response = await self._client.chat.completions.create(
            model=self.model,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": USER_PROMPT},
            ],
            temperature=0.85,
        )

        content = response.choices[0].message.content
        if not content:
            raise LLMResponseError("OpenAI returned an empty response.")
        return content

    @staticmethod
    def _parse_response(content: str) -> dict[str, str]:
        """Parse and validate the JSON payload returned by the LLM."""
        payload: dict[str, Any] = json.loads(content)
        riddle = str(payload.get("riddle", "")).strip()
        answer = str(payload.get("answer", "")).strip()

        if not riddle:
            raise ValueError("Field 'riddle' must not be empty.")
        if not answer:
            raise ValueError("Field 'answer' must not be empty.")
        if len(riddle) > MAX_RIDDLE_LENGTH:
            raise ValueError(f"Field 'riddle' exceeds {MAX_RIDDLE_LENGTH} characters.")

        return {"riddle": riddle, "answer": answer}
