param(
    [string]$ApiDomain = "api.your-domain.com",
    [string]$FrontendDomain = "your-domain.com",
    [string]$OpenAiKey = "sk-your-openai-api-key-here",
    [string]$Output = ""
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
if (-not $Output) {
    $Output = Join-Path $Root ".env.production.generated"
}

function New-RandomSecret([int]$Length = 32) {
    $bytes = New-Object byte[] $Length
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    [Convert]::ToBase64String($bytes).Replace("+", "").Replace("/", "").Replace("=", "").Substring(0, $Length)
}

$postgresPassword = New-RandomSecret 32
$eraSalt = New-RandomSecret 48

$content = @"
# Generated by scripts/generate-prod-env.ps1 — copy to server as .env
# NEVER commit this file.

POSTGRES_USER=era
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_DB=era_db

DATABASE_URL=postgresql+asyncpg://era:${postgresPassword}@postgres:5432/era_db
DATABASE_URL_SYNC=postgresql+psycopg2://era:${postgresPassword}@postgres:5432/era_db

REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

OPENAI_API_KEY=$OpenAiKey
OPENAI_MODEL=gpt-4o-mini

ERA_SERVER_SALT=$eraSalt

CORS_ORIGINS=https://$FrontendDomain,https://www.$FrontendDomain
"@

Set-Content -Path $Output -Value $content -Encoding UTF8

Write-Host "[ERA] Generated: $Output"
Write-Host "[ERA] API domain: https://$ApiDomain"
Write-Host "[ERA] Frontend build: `$env:VITE_API_URL='https://$ApiDomain'; npm run build"
Write-Host "[ERA] Copy to server: scp $Output user@server:~/ERA/.env"
