#!/usr/bin/env bash
# Generate a production .env file with strong random secrets.
# Usage:
#   bash scripts/generate-prod-env.sh
#   bash scripts/generate-prod-env.sh --api-domain api.example.com --frontend-domain example.com
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DOMAIN="api.your-domain.com"
FRONTEND_DOMAIN="your-domain.com"
OPENAI_KEY="sk-your-openai-api-key-here"
OUTPUT="$ROOT/.env.production.generated"

while [ $# -gt 0 ]; do
  case "$1" in
    --api-domain) API_DOMAIN="$2"; shift 2 ;;
    --frontend-domain) FRONTEND_DOMAIN="$2"; shift 2 ;;
    --openai-key) OPENAI_KEY="$2"; shift 2 ;;
    --output) OUTPUT="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--api-domain DOMAIN] [--frontend-domain DOMAIN] [--openai-key KEY] [--output FILE]"
      exit 0
      ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required."
  exit 1
fi

POSTGRES_PASSWORD="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"
ERA_SERVER_SALT="$(openssl rand -base64 48 | tr -d '/+=' | head -c 48)"

cat > "$OUTPUT" <<EOF
# Generated by scripts/generate-prod-env.sh — copy to server as .env
# NEVER commit this file.

POSTGRES_USER=era
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=era_db

DATABASE_URL=postgresql+asyncpg://era:${POSTGRES_PASSWORD}@postgres:5432/era_db
DATABASE_URL_SYNC=postgresql+psycopg2://era:${POSTGRES_PASSWORD}@postgres:5432/era_db

REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

OPENAI_API_KEY=${OPENAI_KEY}
OPENAI_MODEL=gpt-4o-mini

ERA_SERVER_SALT=${ERA_SERVER_SALT}

CORS_ORIGINS=https://${FRONTEND_DOMAIN},https://www.${FRONTEND_DOMAIN}
EOF

chmod 600 "$OUTPUT" 2>/dev/null || true

echo "[ERA] Generated: $OUTPUT"
echo "[ERA] API domain: https://${API_DOMAIN}"
echo "[ERA] Frontend build: VITE_API_URL=https://${API_DOMAIN} npm run build"
echo "[ERA] Copy to server: scp $OUTPUT user@server:~/ERA/.env"
